const articles = [
  {
    imgSrc: './src/img/img1.jpg',
    imgSrcSet: './src/img/img1.jpg 1x, ./src/img/img1@2x.jpg 2x',
    imgAlt: 'Orange sofa in a room',
    authorImg: './src/img/orange.jpeg',
    authorName: 'Dianne Russell',
    title: 'The things we need to check when we want to buy a house',
    time: '4 min read | 25 Apr 2021',
  },
  {
    imgSrc: './src/img/img2.jpg',
    imgSrcSet: './src/img/img2.jpg 1x, ./src/img/img2@2x.jpg 2x',
    imgAlt: 'House with big yard',
    authorImg: './src/img/Courtney.jpeg',
    authorName: 'Courtney Henry',
    title: '7 Ways to distinguish the quality of the house we want to buy',
    time: '6 min read | 24 Apr 2021',
  },
  {
    imgSrc: './src/img/img3.jpg',
    imgSrcSet: './src/img/img3.jpg 1x, ./src/img/img3@2x.jpg 2x',
    imgAlt: 'Sunny house',
    authorImg: './src/img/Darlene.jpeg',
    authorName: 'Darlene Robertson',
    title: 'The best way to know the quality of the house we want to buy',
    time: '2 min read | 24 Apr 2021',
  },
  {
    imgSrc: './src/img/house4.jpg',
    imgSrcSet: './src/img/house4.jpg 1x, ./src/img/house4@2x.jpg 2x',
    imgAlt: 'Cozy white house',
    authorImg: './src/img/Ronald.png',
    authorName: 'Ronald Richards',
    title: 'How to prepare your house for selling',
    time: '7 min read | 24 Apr 2021',
  },
  {
    imgSrc: './src/img/grey.jpg',
    imgSrcSet: './src/img/grey.jpg 1x, ./src/img/grey@2x.jpg 2x',
    imgAlt: 'Big house with beautiful yard',
    authorImg: './src/img/Dianne.png',
    authorName: 'Dianne Russel',
    title: 'How to choose your dream home',
    time: '5 min read | 25 Apr 2021',
  },
  {
    imgSrc: './src/img/red-house.jpg',
    imgSrcSet: './src/img/red-house.jpg 1x, ./src/img/red-house@2x.jpg 2x',
    imgAlt: 'Ideal house for family',
    authorImg: './src/img/blonde.jpeg',
    authorName: 'Esther Howard',
    title: 'Why location matters when buying a home',
    time: '6 min read | 26 Apr 2021',
  },
  {
    imgSrc: './src/img/img1.jpg',
    imgSrcSet: './src/img/img1.jpg 1x, ./src/img/img1@2x.jpg 2x',
    imgAlt: 'Modern living room',
    authorImg: './src/img/blonde.jpeg',
    authorName: 'Mandy Howard',
    title: 'The things we need to check when we want to buy a flat',
    time: '6 min read | 27 Apr 2021',
  },
  {
    imgSrc: './src/img/img2.jpg',
    imgSrcSet: './src/img/img2.jpg 1x, ./src/img/img2@2x.jpg 2x',
    imgAlt: 'House with big yard',
    authorImg: './src/img/Courtney.jpeg',
    authorName: 'Maftuna Wethers',
    title: 'The best companies to renovate your home',
    time: '5 min read | 28 Apr 2021',
  },
  {
    imgSrc: './src/img/red-house.jpg',
    imgSrcSet: './src/img/red-house.jpg 1x, ./src/img/red-house@2x.jpg 2x',
    imgAlt: 'Ideal house for family',
    authorImg: './src/img/Darlene.jpeg',
    authorName: 'Jack Daniels',
    title: 'Top 10 mistakes to avoid when buying a home',
    time: '6 min read | 29 Apr 2021',
  },
];

export default articles;
